#!/bin/bash

#unset DISPLAY
#export JAVA_OPTS="-Xms256m -Xmx256m"
export X509_USER_PROXY=~/.grid/grid.proxy
java ${JAVA_OPTS} -cp /usr/local/lib/grisu/nesi-setup-binary.jar grisu.frontend.view.swing.utils.ssh.wizard.NesiSetupWizard "$@"

